### ISSUE TITLE
Where is "params.json" required by "render_models.py"

### ISSUE THREAD

**Issue by ildefons** [rstrivedi/Melting-Pot-Contest-2023#9]
I am trying to run the baseline. when running the rendering rutine I get the following error:
Call:
`python baselines/train/render_models.py --config_dir ./`
Error:
```
Traceback (most recent call last):
  File "/home/ildefons/aicrowd/Melting-Pot-Contest-2023/baselines/train/render_models.py", line 94, in <module>
    render_model(args)
  File "/home/ildefons/aicrowd/Melting-Pot-Contest-2023/baselines/train/render_models.py", line 17, in render_model
    f = open(config_file)
```

I basically cannot find the params.json file. Where is it?

**Comment by rstrivedi** [comment]
Hi ildefons,

params.json will be created after you have run training script. It is output by the training module. It will be located in directory where you store the results of your training. For example, if your results directory is located in baselines/train/results/<exp_name> then you will find params.json in <exp_name>/PPO_*/ folder if you run PPO algorithm which is default with this baseline. You need to have trained the model to use the rendering part.
